# Generated by Django 2.1.2 on 2018-10-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perro', '0002_perrito_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='foto_perro',
            field=models.ImageField(default='DEFAULT_VALUE', upload_to='img'),
        ),
    ]
